development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: MyDatabase
  username: root
  password: password
  host: rmkoo0bk6s32mc.cogbsxdqpjfs.us-west-2.rds.amazonaws.com
  port: 3306
